services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    restart: unless-stopped
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_PORT}:${PHPMYADMIN_PORT}"
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MEMORY_LIMIT: '-1'
      MAX_EXECUTION_TIME: 0
      APACHE_PORT: ${PHPMYADMIN_PORT}
      UPLOAD_LIMIT: '10G'
    depends_on:
      - mysql
    networks:
      - network

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./data/redis:/data/redis
    networks:
      - network

  queue-worker:
    container_name: queue-worker
    image: php:cli-alpine
    working_dir: /app
    command: php /app/artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600
    restart: always
    volumes:
      - ./:/app
    networks:
      - network

  schedule-worker:
    container_name: schedule-worker
    image: php:cli-alpine
    working_dir: /app
    command: php /app/artisan schedule:work
    restart: always
    volumes:
      - ./:/app
    networks:
      - network


networks:
  network:
