services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./data/redis:/data/redis
    networks:
      - network

  queue-worker:
    container_name: queue-worker
    image: php:cli-alpine
    working_dir: /app
    command: php /app/artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600
    restart: always
    volumes:
      - ./:/app
    networks:
      - network

  schedule-worker:
    container_name: schedule-worker
    image: php:cli-alpine
    working_dir: /app
    command: php /app/artisan schedule:work
    restart: always
    volumes:
      - ./:/app
    networks:
      - network


networks:
  network:
